### ISSUE TITLE
CV.OCD firmware build instructions

### ISSUE THREAD

**Issue by boourns** [hotchk155/cvocd.a#7]
Hi,

I'm working on a tiny personal modification of the CV.OCD firmware.  I need gates 1 and 2 to be inverted - +5v when off, 0v when on.  I tried an s-trig cable like you suggested in our tindie communication but once a cable is plugged into the Yamaha CS-40M it starts looking at the voltage, it seems.

I'm a software developer so I'm happy to do this myself but I'm looking for a few hints how to build the firmware .syx.  I'll try to document it in the meantime for anyone looking to follow in my shoes.

- obtain windows machine or VM
- install latest SourceBoost package - http://www.sourceboost.com/CommonDownload.html
- git clone this repo
- install visual studio 2015 runtime for your version of windows
- build project
  - open cvocd.__c as workspace
  - (if necessary) open cvocd.__c as file and edit the BoostDir
- run hex2sys (id?)

Outstanding questions:
- how do I build the entire project?  There doesn't seem to be a project file to open, and when I open one file in the directory and build it, I end up building interrupt.o successfully, but I'm unsure if that's the entire binary or just one object file compiled.
- what is the correct invocation of hex2sys?

Thanks,
Tom

**Comment by hotchk155** [comment]
Hey Tom

I have a feeling that the free version of sourceboost C might have a limitation on image size, which could be an issue.
The project file is the *.__c file and when configured correctly you just open this in BoostC IDE and you can build with F7. The output should be a .hex file
I think the limited version might stop at the link stage while might mean you get object files (*.o) but no compiled hex file.

Hex2syx needs to be run with command line hex2syx a <path to hex file> <target path to sysex file>
The “a” parameter makes sure the correct format for cvocd is built.
Since this has really just been a tool for my own use it’s a bit scrappy and undocumented but there isn’t too much to it.

Now, a couple of complications you might come across are

  *   The code space is very tight against the 8k FLASH limit on the PIC (some of which is reserved for the bootloader) and you may need to strip out some code if your changes add much to the size of the binary.
  *   There is a “deferred gate” mechanism in the code which is used when a gate is tied to a CV. The idea is that the gate is not triggered until the new CV value has been sent out to the DAC, so that the CV is present before the associated gate edge. IIRC this is a slight complication when trying to change the code to use negative gates, not an insurmountable huge problem but something to watch out for.

I have been thinking of adding this functionality already, so I might go back and remind myself of how I thought it should be done

Cheers
Jason

**Comment by boourns** [comment]
Aww, yeah it looks like it would work except the license restriction blocks it.  That's unfortunate.

**Comment by hotchk155** [comment]
I have a fix which I can email to you. FYI the code change I used was as follows

1. Move the following from GATE.c to CVOCD.h

// Define bits for the shift register outputs
#define SRB_NOTE1       0x0004
#define SRB_NOTE2       0x0008
#define SRB_NOTE3        0x0002
#define SRB_NOTE4       0x0001
#define SRB_DRM1         0x0100
#define SRB_DRM2         0x0200
#define SRB_DRM3         0x0400
#define SRB_DRM4         0x0800
#define SRB_DRM5         0x1000
#define SRB_DRM6         0x2000
#define SRB_DRM7         0x4000
#define SRB_DRM8         0x8000

2. In CVOCD.C

////////////////////////////////////////////////////////////
// LOAD GATE SHIFT REGISTER
void sr_write(unsigned int nmask) {
                unsigned int d = g_sr_data & ~nmask; // nmask is a bit set to force to LOW
                d ^= (SRB_NOTE1|SRB_NOTE2);  // **** This Line Added *****
                unsigned int m1 = 0x0080;
                unsigned int m2 = 0x8000;
                P_SRLAT = 0;
                while(m1) {
                                P_SRCLK = 0;
                                P_SRDAT1 = !!(d&m1);
                                P_SRDAT2 = !!(d&m2);
                                P_SRCLK = 1;
                                m1>>=1;
                                m2>>=1;
                }
                P_SRLAT = 1;
}

3. In GATE.C

////////////////////////////////////////////////////////////
// SET DEFAULT GATE STATE
void gate_reset() {
                for(byte which_gate=0; which_gate<GATE_MAX; ++which_gate) {
                                GATE_OUT_CFG *pcfg = &l_gate_cfg[which_gate];
                                GATE_OUT *pgate = &l_gate[which_gate];
                                pgate->counter = 0;
                                switch(pcfg->event.mode) {
                                                case GATE_MIDI_CLOCK_TICK:
                                                case GATE_MIDI_CLOCK_RUN_TICK:
                                                                pgate->value = pcfg->clock.tick_ofs;
                                                                break;
                                                default:
                                                                pgate->value = NO_VALUE;
                                                                break;
                                }
                                trigger(pgate, pcfg, which_gate, false, false);
                }
                g_sr_data_pending = 1; // *** This Line Added ****
}


Change (3) makes sure that the inverted gates are set ON when the gate states are reset

This is hardcoded to work on gates 1+2 but I have a larger change that allows configuration of inverted gates via Sysex but there is insufficient ROM space for the change without removing other features. It would be good to see if this approach works in practice first!

**Comment by boourns** [comment]
Hahaha oh man.

So I just tried it, and at first it was emitting a fixed 5v.  I went through my whole MIDI setup, starting testing all my assumptions, and about 20 minutes later it hit me that very likely after flashing the firmware it nuked my sysex settings.

Sure enough, reflash and now it is working absolutely perfectly.  This is awesome.

Thank you so much!

**Comment by hotchk155** [comment]
No worries mate – let me know if you hit any issues and I will keep this feature (in a more configurable form) in mind for future releases
Cheers
Jason
